{% set version = "2.2.1" %}
{% set sha256 = "398bba9e7fa25e2ce144c5c4b8ec6208e89b9445869403dfa88ab66ec110fa12" %}

package:
  name: addict
  version: {{ version }}

source:
    url: https://github.com/mewwts/addict/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - addict

about:
  home: https://github.com/mewwts/addict
  license: MIT
  license_file: LICENSE
  summary: 'Addict is a dictionary whose items can be set using both attribute and item syntax.'

extra:
  recipe-maintainers:
    - Ohjeah
