{% set version = "2.3.0" %}
{% set sha256 = "7c0c6a4f8162be84eec98ba089ab4845db56c62954b5701f350e61124da04cb8" %}

package:
  name: addict
  version: {{ version }}

source:
  url: https://github.com/mewwts/addict/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - addict

about:
  home: https://github.com/mewwts/addict
  license: MIT
  license_file: LICENSE
  summary: Addict is a dictionary whose items can be set using both attribute and item syntax.

extra:
  recipe-maintainers:
    - Ohjeah
